const TOPICS = [
  "science",
  "culture",
  "technology",
  "animation",
  "business",
  "health",
  "society",
  "brain",
  "social change",
  "psychology",
  "global issues",
  "humanity",
  "education",
  "entertainment",
  "design",
  "history",
  "biology",
  "communication",
  "creativity",
  "personal growth",
  "innovation",
  "future",
  "work",
  "human body",
  "medicine",
  "community",
  "collaboration",
  "children",
  "health care",
  "economics",
  "identity",
  "mental health",
  "happiness",
  "art",
  "math",
  "life",
  "nature",
  "invention",
  "activism",
  "motivation",
  "animals",
  "leadership",
  "mind",
  "self",
  "storytelling",
  "environment",
  "humor",
  "writing",
  "public health",
  "success",
  "neuroscience",
  "music",
  "women",
  "politics",
  "TED Fellows",
  "performance",
  "physiology",
  "evolution",
  "medical research",
  "computers",
  "disease",
  "climate change",
  "exploration",
  "inequality",
  "data",
  "engineering",
  "philosophy",
  "language",
  "Internet",
  "relationships",
  "physics",
  "universe",
  "visualizations",
  "cognitive science",
  "teaching",
  "decision-making",
  "space",
  "war",
  "entrepreneur",
  "food",
  "parenting",
  "love",
  "goal-setting",
  "choice",
  "Africa",
  "world cultures",
  "sustainability",
  "depression",
  "family",
  "government",
  "potential",
  "memory",
  "cities",
  "live music",
  "photography",
  "healthcare",
  "religion",
  "illness",
  "United States",
  "comedy",
  "consciousness",
  "oceans",
  "sex",
  "aging",
  "intelligence",
  "beauty",
  "demo",
  "social media",
  "books",
  "productivity",
  "time",
  "race",
  "anthropology",
  "death",
  "personality",
  "ancient world",
  "AI",
  "dance",
  "poetry",
  "violence",
  "global development",
  "robots",
  "gender equality",
  "democracy",
  "architecture",
  "energy",
  "policy",
  "media",
  "literature",
  "genetics",
  "fear",
  "crime",
  "money",
  "sociology",
  "work-life balance",
  "body language",
  "biotech",
  "film",
  "algorithm",
  "product design",
  "biodiversity",
  "curiosity",
  "big problems",
  "water",
  "astronomy",
  "peace",
  "pollution",
  "compassion",
  "emotions",
  "online video",
  "feminism",
  "adventure",
  "youth",
  "mindfulness",
  "green",
  "speech",
  "gender",
  "law",
  "journalism",
  "infrastructure",
  "Asia",
  "software",
  "Planets",
  "sound",
  "magic",
  "DNA",
  "cancer",
  "poverty",
  "empathy",
  "cosmos",
  "china",
  "disability",
  "chemistry",
  "sports",
  "addiction",
  "prison",
  "insects",
  "TEDMED",
  "women in business",
  "science and art",
  "statistics",
  "ecology",
  "Middle East",
  "faith",
  "india",
  "machine learning",
  "investment",
  "marine biology",
  "performance art",
  "fashion",
  "agriculture",
  "gaming",
  "web",
  "Best of the Web",
  "friendship",
  "illusion",
  "nanoscale",
  "bacteria",
  "biomechanics",
  "failure",
  "materials",
  "morality",
  "behavioral economics",
  "TED Books",
  "industrial design",
  "exercise",
  "NASA",
  "code",
  "justice system",
  "transportation",
  "movies",
  "spoken word",
  "plants",
  "alternative energy",
  "fish",
  "electricity",
  "sleep",
  "open-source",
  "extraterrestrial life",
  "security",
  "manufacturing",
  "String theory",
  "military",
  "disaster relief",
  "interface design",
  "finance",
  "privacy",
  "urban planning",
  "natural resources",
  "introvert",
  "drones",
  "Anthropocene",
  "public spaces",
  "ebola",
  "dark matter",
  "terrorism",
  "philanthropy",
  "consumerism",
  "discovery",
  "microbiology",
  "obesity",
  "molecular biology",
  "solar energy",
  "criminal justice",
  "interview",
  "God",
  "play",
  "marketing",
  "TED Residency",
  "book",
  "sight",
  "programming",
  "flight",
  "virus",
  "suicide",
  "hack",
  "bioethics",
  "solar system",
  "LGBT",
  "corruption",
  "Mars",
  "encryption",
  "human origins",
  "big bang",
  "pain",
  "evolutionary psychology",
  "Slavery",
  "prosthetics",
  "news",
  "Europe",
  "refugees",
  "natural disaster",
  "quantum physics",
  "immigration",
  "trust",
  "aircraft",
  "sexual violence",
  "novel",
  "complexity",
  "telescopes",
  "Senses",
  "meditation",
  "surveillance",
  "Buddhism",
  "heart health",
  "TED Prize",
  "biosphere",
  "garden",
  "library",
  "weather",
  "TEDNYC",
  "capitalism",
  "men",
  "TEDYouth",
  "narcotics",
  "pregnancy",
  "cars",
  "biomimicry",
  "indigenous peoples",
  "theater",
  "Google",
  "microbes",
  "prediction",
  "pharmaceuticals",
  "conservation",
  "farming",
  "trees",
  "diversity",
  "Transgender",
  "Surgery",
  "toy",
  "astrobiology",
  "fungi",
  "medical imaging",
  "virtual reality",
  "botany",
  "conducting",
  "Vaccines",
  "neurology",
  "television",
  "geology",
  "birds",
  "resources",
  "bionics",
  "Autism spectrum disorder",
  "paleontology",
  "painting",
  "extreme sports",
  "travel",
  "simplicity",
  "synthetic biology",
  "population",
  "funny",
  "Christianity",
  "blindness",
  "TED-Ed",
  "presentation",
  "guns",
  "map",
  "plastic",
  "South America",
  "nuclear energy",
  "Audacious Project",
  "composing",
  "asteroid",
  "bullying",
  "Antarctica",
  "advertising",
  "Gender spectrum",
  "monkeys",
  "driverless cars",
  "mission blue",
  "global commons",
  "rocket science",
  "protests",
  "HIV",
  "bees",
  "singer",
  "Debate",
  "atheism",
  "markets",
  "MacArthur grant",
  "CRISPR",
  "submarine",
  "Islam",
  "3D printing",
  "trafficking",
  "urban",
  "AIDS",
  "Egypt",
  "vocals",
  "wunderkind",
  "PTSD",
  "rivers",
  "Foreign Policy",
  "blockchain",
  "cryptocurrency",
  "dinosaurs",
  "guitar",
  "museums",
  "TED en Español",
  "archaeology",
  "glacier",
  "shopping",
  "Alzheimer's",
  "student",
  "crowdsourcing",
  "vulnerability",
  "science fiction",
  "Brazil",
  "sanitation",
  "Nobel Prize",
  "graphic design",
  "iraq",
  "smell",
  "hearing",
  "mobility",
  "human rights",
  "development",
  "grammar",
  "piano",
  "primates",
  "apes",
  "arts",
  "Moon",
  "Iran",
  "evil",
  "wikipedia",
  "Syria",
  "pandemic",
  "coral reefs",
  "ants",
  "Latin America",
  "deextinction",
  "microsoft",
  "Brand",
  "telecom",
  "state-building",
  "wind energy",
  "violin",
  "opioids",
  "augmented reality",
  "homelessness",
  "jazz",
  "typography",
  "forensics",
  "Sun",
  "nuclear weapons",
  "coronavirus",
  "meme",
  "cooperation",
  "epidemiology",
  "New York",
  "oil",
  "start-up",
  "nonviolence",
  "mining",
  "street art",
  "TEDx",
  "inclusion",
  "rap",
  "microfinance",
  "charter for compassion",
  "cloud",
  "origami",
  "robot",
  "skateboarding",
  "Social Science",
  "exoskeleton",
  "cello",
  "Humanities",
  "stigma",
  "testing",
  "gay",
  "Science (hard)",
];
 
export { TOPICS }