import { Schema, model } from "mongoose";

const topics = {
  science: 0,
  culture: 0,
  technology: 0,
  animation: 0,
  business: 0,
  health: 0,
  society: 0,
  brain: 0,
  "social change": 0,
  psychology: 0,
  "global issues": 0,
  humanity: 0,
  education: 0,
  entertainment: 0,
  design: 0,
  history: 0,
  biology: 0,
  communication: 0,
  creativity: 0,
  "personal growth": 0,
  innovation: 0,
  future: 0,
  work: 0,
  "human body": 0,
  medicine: 0,
  community: 0,
  collaboration: 0,
  children: 0,
  "health care": 0,
  economics: 0,
  identity: 0,
  "mental health": 0,
  happiness: 0,
  art: 0,
  math: 0,
  life: 0,
  nature: 0,
  invention: 0,
  activism: 0,
  motivation: 0,
  animals: 0,
  leadership: 0,
  mind: 0,
  self: 0,
  storytelling: 0,
  environment: 0,
  humor: 0,
  writing: 0,
  "public health": 0,
  success: 0,
  neuroscience: 0,
  music: 0,
  women: 0,
  politics: 0,
  "TED Fellows": 0,
  performance: 0,
  physiology: 0,
  evolution: 0,
  "medical research": 0,
  computers: 0,
  disease: 0,
  "climate change": 0,
  exploration: 0,
  inequality: 0,
  data: 0,
  engineering: 0,
  philosophy: 0,
  language: 0,
  Internet: 0,
  relationships: 0,
  physics: 0,
  universe: 0,
  visualizations: 0,
  "cognitive science": 0,
  teaching: 0,
  "decision-making": 0,
  space: 0,
  war: 0,
  entrepreneur: 0,
  food: 0,
  parenting: 0,
  love: 0,
  "goal-setting": 0,
  choice: 0,
  Africa: 0,
  "world cultures": 0,
  sustainability: 0,
  depression: 0,
  family: 0,
  government: 0,
  potential: 0,
  memory: 0,
  cities: 0,
  "live music": 0,
  photography: 0,
  healthcare: 0,
  religion: 0,
  illness: 0,
  "United States": 0,
  comedy: 0,
  consciousness: 0,
  oceans: 0,
  sex: 0,
  aging: 0,
  intelligence: 0,
  beauty: 0,
  demo: 0,
  "social media": 0,
  books: 0,
  productivity: 0,
  time: 0,
  race: 0,
  anthropology: 0,
  death: 0,
  personality: 0,
  "ancient world": 0,
  AI: 0,
  dance: 0,
  poetry: 0,
  violence: 0,
  "global development": 0,
  robots: 0,
  "gender equality": 0,
  democracy: 0,
  architecture: 0,
  energy: 0,
  policy: 0,
  media: 0,
  literature: 0,
  genetics: 0,
  fear: 0,
  crime: 0,
  money: 0,
  sociology: 0,
  "work-life balance": 0,
  "body language": 0,
  biotech: 0,
  film: 0,
  algorithm: 0,
  "product design": 0,
  biodiversity: 0,
  curiosity: 0,
  "big problems": 0,
  water: 0,
  astronomy: 0,
  peace: 0,
  pollution: 0,
  compassion: 0,
  emotions: 0,
  "online video": 0,
  feminism: 0,
  adventure: 0,
  youth: 0,
  mindfulness: 0,
  green: 0,
  speech: 0,
  gender: 0,
  law: 0,
  journalism: 0,
  infrastructure: 0,
  Asia: 0,
  software: 0,
  Planets: 0,
  sound: 0,
  magic: 0,
  DNA: 0,
  cancer: 0,
  poverty: 0,
  empathy: 0,
  cosmos: 0,
  china: 0,
  disability: 0,
  chemistry: 0,
  sports: 0,
  addiction: 0,
  prison: 0,
  insects: 0,
  TEDMED: 0,
  "women in business": 0,
  "science and art": 0,
  statistics: 0,
  ecology: 0,
  "Middle East": 0,
  faith: 0,
  india: 0,
  "machine learning": 0,
  investment: 0,
  "marine biology": 0,
  "performance art": 0,
  fashion: 0,
  agriculture: 0,
  gaming: 0,
  web: 0,
  "Best of the Web": 0,
  friendship: 0,
  illusion: 0,
  nanoscale: 0,
  bacteria: 0,
  biomechanics: 0,
  failure: 0,
  materials: 0,
  morality: 0,
  "behavioral economics": 0,
  "TED Books": 0,
  "industrial design": 0,
  exercise: 0,
  NASA: 0,
  code: 0,
  "justice system": 0,
  transportation: 0,
  movies: 0,
  "spoken word": 0,
  plants: 0,
  "alternative energy": 0,
  fish: 0,
  electricity: 0,
  sleep: 0,
  "open-source": 0,
  "extraterrestrial life": 0,
  security: 0,
  manufacturing: 0,
  "String theory": 0,
  military: 0,
  "disaster relief": 0,
  "interface design": 0,
  finance: 0,
  privacy: 0,
  "urban planning": 0,
  "natural resources": 0,
  introvert: 0,
  drones: 0,
  Anthropocene: 0,
  "public spaces": 0,
  ebola: 0,
  "dark matter": 0,
  terrorism: 0,
  philanthropy: 0,
  consumerism: 0,
  discovery: 0,
  microbiology: 0,
  obesity: 0,
  "molecular biology": 0,
  "solar energy": 0,
  "criminal justice": 0,
  interview: 0,
  God: 0,
  play: 0,
  marketing: 0,
  "TED Residency": 0,
  book: 0,
  sight: 0,
  programming: 0,
  flight: 0,
  virus: 0,
  suicide: 0,
  hack: 0,
  bioethics: 0,
  "solar system": 0,
  LGBT: 0,
  corruption: 0,
  Mars: 0,
  encryption: 0,
  "human origins": 0,
  "big bang": 0,
  pain: 0,
  "evolutionary psychology": 0,
  Slavery: 0,
  prosthetics: 0,
  news: 0,
  Europe: 0,
  refugees: 0,
  "natural disaster": 0,
  "quantum physics": 0,
  immigration: 0,
  trust: 0,
  aircraft: 0,
  "sexual violence": 0,
  novel: 0,
  complexity: 0,
  telescopes: 0,
  Senses: 0,
  meditation: 0,
  surveillance: 0,
  Buddhism: 0,
  "heart health": 0,
  "TED Prize": 0,
  biosphere: 0,
  garden: 0,
  library: 0,
  weather: 0,
  TEDNYC: 0,
  capitalism: 0,
  men: 0,
  TEDYouth: 0,
  narcotics: 0,
  pregnancy: 0,
  cars: 0,
  biomimicry: 0,
  "indigenous peoples": 0,
  theater: 0,
  Google: 0,
  microbes: 0,
  prediction: 0,
  pharmaceuticals: 0,
  conservation: 0,
  farming: 0,
  trees: 0,
  diversity: 0,
  Transgender: 0,
  Surgery: 0,
  toy: 0,
  astrobiology: 0,
  fungi: 0,
  "medical imaging": 0,
  "virtual reality": 0,
  botany: 0,
  conducting: 0,
  Vaccines: 0,
  neurology: 0,
  television: 0,
  geology: 0,
  birds: 0,
  resources: 0,
  bionics: 0,
  "Autism spectrum disorder": 0,
  paleontology: 0,
  painting: 0,
  "extreme sports": 0,
  travel: 0,
  simplicity: 0,
  "synthetic biology": 0,
  population: 0,
  funny: 0,
  Christianity: 0,
  blindness: 0,
  "TED-Ed": 0,
  presentation: 0,
  guns: 0,
  map: 0,
  plastic: 0,
  "South America": 0,
  "nuclear energy": 0,
  "Audacious Project": 0,
  composing: 0,
  asteroid: 0,
  bullying: 0,
  Antarctica: 0,
  advertising: 0,
  "Gender spectrum": 0,
  monkeys: 0,
  "driverless cars": 0,
  "mission blue": 0,
  "global commons": 0,
  "rocket science": 0,
  protests: 0,
  HIV: 0,
  bees: 0,
  singer: 0,
  Debate: 0,
  atheism: 0,
  markets: 0,
  "MacArthur grant": 0,
  CRISPR: 0,
  submarine: 0,
  Islam: 0,
  "3D printing": 0,
  trafficking: 0,
  urban: 0,
  AIDS: 0,
  Egypt: 0,
  vocals: 0,
  wunderkind: 0,
  PTSD: 0,
  rivers: 0,
  "Foreign Policy": 0,
  blockchain: 0,
  cryptocurrency: 0,
  dinosaurs: 0,
  guitar: 0,
  museums: 0,
  "TED en Español": 0,
  archaeology: 0,
  glacier: 0,
  shopping: 0,
  "Alzheimer's": 0,
  student: 0,
  crowdsourcing: 0,
  vulnerability: 0,
  "science fiction": 0,
  Brazil: 0,
  sanitation: 0,
  "Nobel Prize": 0,
  "graphic design": 0,
  iraq: 0,
  smell: 0,
  hearing: 0,
  mobility: 0,
  "human rights": 0,
  development: 0,
  grammar: 0,
  piano: 0,
  primates: 0,
  apes: 0,
  arts: 0,
  Moon: 0,
  Iran: 0,
  evil: 0,
  wikipedia: 0,
  Syria: 0,
  pandemic: 0,
  "coral reefs": 0,
  ants: 0,
  "Latin America": 0,
  deextinction: 0,
  microsoft: 0,
  Brand: 0,
  telecom: 0,
  "state-building": 0,
  "wind energy": 0,
  violin: 0,
  opioids: 0,
  "augmented reality": 0,
  homelessness: 0,
  jazz: 0,
  typography: 0,
  forensics: 0,
  Sun: 0,
  "nuclear weapons": 0,
  coronavirus: 0,
  meme: 0,
  cooperation: 0,
  epidemiology: 0,
  "New York": 0,
  oil: 0,
  "start-up": 0,
  nonviolence: 0,
  mining: 0,
  "street art": 0,
  TEDx: 0,
  inclusion: 0,
  rap: 0,
  microfinance: 0,
  "charter for compassion": 0,
  cloud: 0,
  origami: 0,
  robot: 0,
  skateboarding: 0,
  "Social Science": 0,
  exoskeleton: 0,
  cello: 0,
  Humanities: 0,
  stigma: 0,
  testing: 0,
  gay: 0,
  "Science (hard)": 0,
}

const TopicPrioritySchema = new Schema({
  user_id: {
    type: Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  priority: {
    type: Map,
    of: Number,
    default: topics,
  },
});

const TopicPriorityModel = model("TopicPriority", TopicPrioritySchema);

export { TopicPriorityModel };

